import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "./components/layouts/Header";
import { Poppins } from "next/font/google";
import Footer from "./components/layouts/Footer";
import Provider from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <Header />
          <div className="">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
